image: Ubuntu  # Используем образ Ubuntu для сборки

stack: jdk 11  # Версия JDK

branches:
  only:
    - master  # Выполняем сборку только для ветки master

services:
  - docker  # Включаем сервис Docker

install:
  # Проверяем доступность Docker
  - docker --version
  - docker-compose --version

  # Запускаем MySQL через docker-compose
  - docker-compose up -d

  # Проверяем статус контейнеров
  - echo "Проверяем работающие контейнеры:"
  - docker ps

  # Ждём, пока MySQL станет доступен
  - echo "Ждём готовности MySQL..."
  - sleep 30

  # Проверяем доступность базы данных
  - echo "Проверяем доступность базы данных..."
  - |
    docker exec $(docker ps -qf "name=mysql") mysql -uuser -ppass -e "SHOW DATABASES;" || echo "Не удалось подключиться к базе данных"

  # Запускаем приложение
  - chmod +x gradlew
  - java -jar ./artifacts/aqa-shop.jar &

build_script:
  # Запускаем тесты
  - ./gradlew test --info -Dselenide.headless=true